/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksSlugRouteRouteImport } from './routes/works.$slug/route'
import { Route as WorksCategorySlugRouteRouteImport } from './routes/works.$category.$slug/route'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRouteRoute = WorksSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorksRoute,
} as any)
const WorksCategorySlugRouteRoute = WorksCategorySlugRouteRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => WorksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/works': typeof WorksRouteWithChildren
  '/works/$slug': typeof WorksSlugRouteRoute
  '/works/$category/$slug': typeof WorksCategorySlugRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/works': typeof WorksRouteWithChildren
  '/works/$slug': typeof WorksSlugRouteRoute
  '/works/$category/$slug': typeof WorksCategorySlugRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/works': typeof WorksRouteWithChildren
  '/works/$slug': typeof WorksSlugRouteRoute
  '/works/$category/$slug': typeof WorksCategorySlugRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/works'
    | '/works/$slug'
    | '/works/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/works'
    | '/works/$slug'
    | '/works/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/works'
    | '/works/$slug'
    | '/works/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  WorksRoute: typeof WorksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteRouteImport
      parentRoute: typeof WorksRoute
    }
    '/works/$category/$slug': {
      id: '/works/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/works/$category/$slug'
      preLoaderRoute: typeof WorksCategorySlugRouteRouteImport
      parentRoute: typeof WorksRoute
    }
  }
}

interface WorksRouteChildren {
  WorksSlugRouteRoute: typeof WorksSlugRouteRoute
  WorksCategorySlugRouteRoute: typeof WorksCategorySlugRouteRoute
}

const WorksRouteChildren: WorksRouteChildren = {
  WorksSlugRouteRoute: WorksSlugRouteRoute,
  WorksCategorySlugRouteRoute: WorksCategorySlugRouteRoute,
}

const WorksRouteWithChildren = WorksRoute._addFileChildren(WorksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  WorksRoute: WorksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
